### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by vanshjangir** [vanshjangir/xdb#1]
### Features
- [x] Query parser and executor.
- [ ] Concurrency.
- [ ] TCP Server on top of the database.
- [ ] Add tests.
- [x] Meta table to store info of all the tables.

### Bugs
- [x] Bug in deletion.
- [x] No of keys in a node should be based on the max size of a row.
- [ ] Support for multi page nodes.
- [ ] Current freelist is only a single page, redesign to make a freelist with multiple pages to store any number of pointers.

### Optimizations
- [ ] Binary search within a node to search a key.
- [ ] Re-designing point queries as just a special case of range queries.

### Tests
- [ ] Test for B+Tree implementation.
- [ ] Test for disk interaction (creating and manipulating files).
- [ ] Test for simulating disk and power failures.
- [ ] Test for transactions.
